# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    apply_arithmetic_operation as apply_arithmetic_operation,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import process_events_details as process_events_details
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_bar_chart as draw_bar_chart
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_icmbio.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_icmbio.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    cluster_hunting_hotspots as cluster_hunting_hotspots,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    compute_view_from_geodataframes as compute_view_from_geodataframes,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    draw_horizontal_bar_chart as draw_horizontal_bar_chart,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    draw_hunting_density_chart as draw_hunting_density_chart,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    explode_hunting_structures as explode_hunting_structures,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    extract_hunting_fields as extract_hunting_fields,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    extract_quantity_value as extract_quantity_value,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    format_count_and_percent as format_count_and_percent,
)
from ecoscope_workflows_ext_icmbio.tasks import format_time_range as format_time_range
from ecoscope_workflows_ext_icmbio.tasks import (
    gather_icmbio_dashboard as gather_icmbio_dashboard,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    generate_hunting_report as generate_hunting_report,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    prepare_hunting_report_context as prepare_hunting_report_context,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    set_viewport_settings as set_viewport_settings,
)
from ecoscope_workflows_ext_icmbio.tasks import summarize_hotspots as summarize_hotspots
from ecoscope_workflows_ext_icmbio.tasks import wrap_image_as_html as wrap_image_as_html
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    viewport_settings = (
        task(set_viewport_settings)
        .validate()
        .set_task_instance_id("viewport_settings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("viewport_settings") or {}))
        .call()
    )

    events_raw = (
        task(get_events)
        .validate()
        .set_task_instance_id("events_raw")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=["caceria"],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "serial_number",
                "event_details",
                "geometry",
                "reported_by",
            ],
            include_details=True,
            include_display_values=True,
            include_null_geometry=False,
            include_updates=False,
            include_related_events=False,
            force_point_geometry=True,
            raise_on_empty=False,
            **(params.get("events_raw") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_raw,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    events_details_resolved = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("events_details_resolved")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            client=er_client,
            map_to_titles=True,
            ordered=True,
            **(params.get("events_details_resolved") or {}),
        )
        .call()
    )

    events_with_lat_lon = (
        task(add_lat_lon_to_gdf)
        .validate()
        .set_task_instance_id("events_with_lat_lon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_gdf=events_details_resolved,
            **(params.get("events_with_lat_lon") or {}),
        )
        .call()
    )

    events_fields = (
        task(extract_hunting_fields)
        .validate()
        .set_task_instance_id("events_fields")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_with_lat_lon, **(params.get("events_fields") or {}))
        .call()
    )

    total_events = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_fields, **(params.get("total_events") or {}))
        .call()
    )

    total_events_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_events_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Eventos analisados",
            decimal_places=0,
            data=total_events,
            **(params.get("total_events_sv") or {}),
        )
        .call()
    )

    periodo_text = (
        task(format_time_range)
        .validate()
        .set_task_instance_id("periodo_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("periodo_text") or {}))
        .call()
    )

    periodo_sv = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("periodo_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Período", data=periodo_text, **(params.get("periodo_sv") or {}))
        .call()
    )

    locais_ativos_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("locais_ativos_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_fields,
            column="situacao_local",
            values=["Ativo"],
            **(params.get("locais_ativos_events") or {}),
        )
        .call()
    )

    locais_ativos_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("locais_ativos_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=locais_ativos_events, **(params.get("locais_ativos_count") or {}))
        .call()
    )

    locais_ativos_text = (
        task(format_count_and_percent)
        .validate()
        .set_task_instance_id("locais_ativos_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            count=locais_ativos_count,
            total=total_events,
            decimal_places=1,
            **(params.get("locais_ativos_text") or {}),
        )
        .call()
    )

    locais_ativos_sv = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("locais_ativos_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Locais ativos",
            data=locais_ativos_text,
            **(params.get("locais_ativos_sv") or {}),
        )
        .call()
    )

    locais_inativos_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("locais_inativos_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_fields,
            column="situacao_local",
            values=["Inativo"],
            **(params.get("locais_inativos_events") or {}),
        )
        .call()
    )

    locais_inativos_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("locais_inativos_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=locais_inativos_events, **(params.get("locais_inativos_count") or {})
        )
        .call()
    )

    locais_inativos_text = (
        task(format_count_and_percent)
        .validate()
        .set_task_instance_id("locais_inativos_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            count=locais_inativos_count,
            total=total_events,
            decimal_places=1,
            **(params.get("locais_inativos_text") or {}),
        )
        .call()
    )

    locais_inativos_sv = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("locais_inativos_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Locais inativos",
            data=locais_inativos_text,
            **(params.get("locais_inativos_sv") or {}),
        )
        .call()
    )

    infrator_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("infrator_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_fields,
            column="infrator_presente",
            values=["Sim"],
            **(params.get("infrator_events") or {}),
        )
        .call()
    )

    infrator_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("infrator_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=infrator_events, **(params.get("infrator_count") or {}))
        .call()
    )

    infrator_presente_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("infrator_presente_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Eventos com infrator presente",
            decimal_places=0,
            data=infrator_count,
            **(params.get("infrator_presente_sv") or {}),
        )
        .call()
    )

    temporal_bar_chart = (
        task(draw_time_series_bar_chart)
        .validate()
        .set_task_instance_id("temporal_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=events_fields,
            x_axis="time",
            y_axis="id",
            category="event_type_display",
            agg_function="count",
            time_interval="month",
            color_column=None,
            plot_style={"texttemplate": "%{y}", "textposition": "outside"},
            layout_style={
                "showlegend": False,
                "title": None,
                "title_x": 0.5,
                "xaxis": {"title": None},
                "yaxis": {"title": "Número de eventos"},
            },
            **(params.get("temporal_bar_chart") or {}),
        )
        .call()
    )

    temporal_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("temporal_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=temporal_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="temporal_bar_chart",
            **(params.get("temporal_bar_chart_html") or {}),
        )
        .call()
    )

    temporal_bar_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("temporal_bar_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Distribuição mensal dos eventos relacionados à caça",
            data=temporal_bar_chart_html,
            **(params.get("temporal_bar_chart_sv") or {}),
        )
        .call()
    )

    situacao_bar_chart = (
        task(draw_bar_chart)
        .validate()
        .set_task_instance_id("situacao_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=events_fields,
            category="situacao_local",
            bar_chart_configs=[
                {
                    "column": "id",
                    "agg_func": "count",
                    "label": "Quantidade",
                    "show_label": True,
                }
            ],
            layout_kwargs={"title": None, "yaxis": {"title": "Número de eventos"}},
            **(params.get("situacao_bar_chart") or {}),
        )
        .call()
    )

    situacao_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("situacao_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=situacao_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="situacao_bar_chart",
            **(params.get("situacao_bar_chart_html") or {}),
        )
        .call()
    )

    situacao_bar_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("situacao_bar_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Situação observada nos locais de caça",
            data=situacao_bar_chart_html,
            **(params.get("situacao_bar_chart_sv") or {}),
        )
        .call()
    )

    tempo_bar_chart = (
        task(draw_bar_chart)
        .validate()
        .set_task_instance_id("tempo_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=events_fields,
            category="tempo_estimado_display",
            bar_chart_configs=[
                {
                    "column": "id",
                    "agg_func": "count",
                    "label": "Quantidade",
                    "show_label": True,
                }
            ],
            layout_kwargs={"title": None, "yaxis": {"title": "Número de eventos"}},
            **(params.get("tempo_bar_chart") or {}),
        )
        .call()
    )

    tempo_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("tempo_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=tempo_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="tempo_bar_chart",
            **(params.get("tempo_bar_chart_html") or {}),
        )
        .call()
    )

    tempo_bar_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("tempo_bar_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Tempo estimado da atividade nos locais registrados",
            data=tempo_bar_chart_html,
            **(params.get("tempo_bar_chart_sv") or {}),
        )
        .call()
    )

    hunting_structures = (
        task(explode_hunting_structures)
        .validate()
        .set_task_instance_id("hunting_structures")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_fields, **(params.get("hunting_structures") or {}))
        .call()
    )

    estruturas_bar_chart = (
        task(draw_horizontal_bar_chart)
        .validate()
        .set_task_instance_id("estruturas_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=hunting_structures,
            category="estrutura",
            bar_configs=[
                {
                    "column": "id",
                    "agg_func": "count",
                    "label": "Quantidade",
                    "show_label": True,
                }
            ],
            sort_descending=True,
            layout_kwargs={"title": None, "xaxis": {"title": "Número de registros"}},
            **(params.get("estruturas_bar_chart") or {}),
        )
        .call()
    )

    estruturas_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("estruturas_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=estruturas_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="estruturas_bar_chart",
            **(params.get("estruturas_bar_chart_html") or {}),
        )
        .call()
    )

    estruturas_bar_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("estruturas_bar_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Estruturas e evidências registradas",
            data=estruturas_bar_chart_html,
            **(params.get("estruturas_bar_chart_sv") or {}),
        )
        .call()
    )

    acoes_bar_chart = (
        task(draw_horizontal_bar_chart)
        .validate()
        .set_task_instance_id("acoes_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=events_fields,
            category="acao_tomada",
            bar_configs=[
                {
                    "column": "id",
                    "agg_func": "count",
                    "label": "Quantidade",
                    "show_label": True,
                }
            ],
            sort_descending=True,
            layout_kwargs={"title": None, "xaxis": {"title": "Número de eventos"}},
            **(params.get("acoes_bar_chart") or {}),
        )
        .call()
    )

    acoes_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("acoes_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=acoes_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="acoes_bar_chart",
            **(params.get("acoes_bar_chart_html") or {}),
        )
        .call()
    )

    acoes_bar_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("acoes_bar_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Ações adotadas pelas equipes",
            data=acoes_bar_chart_html,
            **(params.get("acoes_bar_chart_sv") or {}),
        )
        .call()
    )

    event_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_fields,
            input_column_name="event_type_display",
            colormap="Set2",
            **(params.get("event_colormap") or {}),
        )
        .call()
    )

    event_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("event_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Tipo de evento", **(params.get("event_legend_title") or {}))
        .call()
    )

    event_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("event_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            legend={
                "title": event_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            layer_style={
                "get_fill_color": "column_color",
                "get_line_color": "column_color",
            },
            **(params.get("event_layer") or {}),
        )
        .call()
    )

    events_map_view_state = (
        task(compute_view_from_geodataframes)
        .validate()
        .set_task_instance_id("events_map_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            viewport=viewport_settings,
            **(params.get("events_map_view_state") or {}),
        )
        .call()
    )

    events_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("events_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=[event_layer],
            tile_layers=base_maps,
            view_state=events_map_view_state,
            static=False,
            title=None,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("events_map") or {}),
        )
        .call()
    )

    events_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("events_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=events_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="hunting_events_map.html",
            filename_suffix=None,
            **(params.get("events_map_url") or {}),
        )
        .call()
    )

    events_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("events_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa geral dos eventos",
            data=events_map_url,
            **(params.get("events_map_widget") or {}),
        )
        .call()
    )

    hotspots_clustered = (
        task(cluster_hunting_hotspots)
        .validate()
        .set_task_instance_id("hotspots_clustered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_fields, **(params.get("hotspots_clustered") or {}))
        .call()
    )

    hotspots_summary = (
        task(summarize_hotspots)
        .validate()
        .set_task_instance_id("hotspots_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=hotspots_clustered, **(params.get("hotspots_summary") or {}))
        .call()
    )

    agrupamentos_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("agrupamentos_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=hotspots_summary, **(params.get("agrupamentos_count") or {}))
        .call()
    )

    agrupamentos_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("agrupamentos_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Agrupamentos espaciais exploratórios",
            decimal_places=0,
            data=agrupamentos_count,
            **(params.get("agrupamentos_sv") or {}),
        )
        .call()
    )

    hotspots_table_renamed = (
        task(map_columns)
        .validate()
        .set_task_instance_id("hotspots_table_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=hotspots_summary,
            retain_columns=[
                "Agrupamento",
                "Eventos",
                "Locais ativos",
                "Coordenada central",
                "Referência descritiva predominante",
            ],
            raise_if_not_found=False,
            drop_columns=None,
            rename_columns=None,
            duplicate_strategy="suffix",
            **(params.get("hotspots_table_renamed") or {}),
        )
        .call()
    )

    hotspots_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("hotspots_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=hotspots_table_renamed,
            columns=None,
            table_config=None,
            **(params.get("hotspots_table") or {}),
        )
        .call()
    )

    hotspots_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("hotspots_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=hotspots_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="hotspots_table",
            **(params.get("hotspots_table_html") or {}),
        )
        .call()
    )

    hotspots_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("hotspots_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Agrupamentos",
            data=hotspots_table_html,
            **(params.get("hotspots_table_sv") or {}),
        )
        .call()
    )

    density_chart_png = (
        task(draw_hunting_density_chart)
        .validate()
        .set_task_instance_id("density_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            events_df=hotspots_clustered,
            hotspots_df=hotspots_summary,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("density_chart_png") or {}),
        )
        .call()
    )

    density_chart_wrapped = (
        task(wrap_image_as_html)
        .validate()
        .set_task_instance_id("density_chart_wrapped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            image_path=density_chart_png, **(params.get("density_chart_wrapped") or {})
        )
        .call()
    )

    density_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("density_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=density_chart_wrapped,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="density_chart",
            **(params.get("density_chart_html") or {}),
        )
        .call()
    )

    density_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("density_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Densidade relativa e agrupamentos espaciais exploratórios",
            data=density_chart_html,
            **(params.get("density_chart_widget") or {}),
        )
        .call()
    )

    patrol_observations = (
        task(get_patrol_observations)
        .validate()
        .set_task_instance_id("patrol_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=5000,
            patrol_types=[],
            status=["done", "active", "overdue", "cancelled"],
            **(params.get("patrol_observations") or {}),
        )
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    relocs = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrols_tz,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_serial_number",
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("relocs") or {}),
        )
        .call()
    )

    relocs_in_bounds = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("relocs_in_bounds")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=relocs,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("relocs_in_bounds") or {}),
        )
        .call()
    )

    trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=relocs_in_bounds,
            trajectory_segment_filter={
                "min_length_meters": 0.001,
                "max_length_meters": 500,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            },
            **(params.get("trajs") or {}),
        )
        .call()
    )

    total_patrols = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_id",
            **(params.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrols_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_patrols_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Número de patrulhas",
            decimal_places=0,
            data=total_patrols,
            **(params.get("total_patrols_sv") or {}),
        )
        .call()
    )

    total_distance = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs, column_name="dist_meters", **(params.get("total_distance") or {})
        )
        .call()
    )

    total_distance_km = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_distance_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_distance,
            **(params.get("total_distance_km") or {}),
        )
        .call()
    )

    total_distance_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_distance_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Km patrulhados",
            decimal_places=2,
            data=total_distance_km,
            **(params.get("total_distance_sv") or {}),
        )
        .call()
    )

    total_time = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs, column_name="timespan_seconds", **(params.get("total_time") or {})
        )
        .call()
    )

    total_hours = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_hours")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="s",
            new_unit="h",
            value=total_time,
            **(params.get("total_hours") or {}),
        )
        .call()
    )

    total_hours_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_hours_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Horas trabalhadas",
            decimal_places=2,
            data=total_hours,
            **(params.get("total_hours_sv") or {}),
        )
        .call()
    )

    active_structures = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("active_structures")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=hunting_structures,
            column="situacao_local",
            values=["Ativo"],
            **(params.get("active_structures") or {}),
        )
        .call()
    )

    estruturas_ativas_count = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("estruturas_ativas_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=active_structures, **(params.get("estruturas_ativas_count") or {}))
        .call()
    )

    total_distance_km_value = (
        task(extract_quantity_value)
        .validate()
        .set_task_instance_id("total_distance_km_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            value=total_distance_km, **(params.get("total_distance_km_value") or {})
        )
        .call()
    )

    tdea_ratio = (
        task(apply_arithmetic_operation)
        .validate()
        .set_task_instance_id("tdea_ratio")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            a=estruturas_ativas_count,
            b=total_distance_km_value,
            operation="divide",
            **(params.get("tdea_ratio") or {}),
        )
        .call()
    )

    tdea_index = (
        task(apply_arithmetic_operation)
        .validate()
        .set_task_instance_id("tdea_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            a=tdea_ratio,
            b=100,
            operation="multiply",
            **(params.get("tdea_index") or {}),
        )
        .call()
    )

    tdea_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("tdea_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="TDEA (estruturas ativas / 100km)",
            decimal_places=2,
            data=tdea_index,
            **(params.get("tdea_sv") or {}),
        )
        .call()
    )

    events_map_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("events_map_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=events_map_url,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("events_map_png") or {}),
        )
        .call()
    )

    temporal_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("temporal_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=temporal_bar_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("temporal_chart_png") or {}),
        )
        .call()
    )

    situacao_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("situacao_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=situacao_bar_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("situacao_chart_png") or {}),
        )
        .call()
    )

    tempo_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("tempo_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=tempo_bar_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("tempo_chart_png") or {}),
        )
        .call()
    )

    estruturas_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("estruturas_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=estruturas_bar_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("estruturas_chart_png") or {}),
        )
        .call()
    )

    acoes_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("acoes_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=acoes_bar_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("acoes_chart_png") or {}),
        )
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        .validate()
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            event_gdf=events_fields,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            **(params.get("download_attachments") or {}),
        )
        .call()
    )

    report_template_path = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_template_path") or {}))
        .call()
    )

    report_context = (
        task(prepare_hunting_report_context)
        .validate()
        .set_task_instance_id("report_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            time_range=time_range,
            total_events=total_events,
            locais_ativos=locais_ativos_text,
            locais_inativos=locais_inativos_text,
            infrator_presente=infrator_count,
            agrupamentos=agrupamentos_count,
            total_patrols=total_patrols,
            total_distance_km=total_distance_km,
            total_hours=total_hours,
            estruturas_ativas=estruturas_ativas_count,
            tdea=tdea_index,
            hotspots=hotspots_table_renamed,
            photo_attachment_paths=download_attachments,
            **(params.get("report_context") or {}),
        )
        .call()
    )

    hunting_report = (
        task(generate_hunting_report)
        .validate()
        .set_task_instance_id("hunting_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context=report_context,
            template_path=report_template_path,
            events_map_png=events_map_png,
            temporal_chart_png=temporal_chart_png,
            situacao_chart_png=situacao_chart_png,
            tempo_chart_png=tempo_chart_png,
            estruturas_chart_png=estruturas_chart_png,
            acoes_chart_png=acoes_chart_png,
            density_chart_png=density_chart_png,
            photo_attachment_paths=download_attachments,
            photo_events=events_fields,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("hunting_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_icmbio_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_events_sv,
                periodo_sv,
                locais_ativos_sv,
                locais_inativos_sv,
                infrator_presente_sv,
                agrupamentos_sv,
                total_patrols_sv,
                total_distance_sv,
                total_hours_sv,
                tdea_sv,
                temporal_bar_chart_sv,
                situacao_bar_chart_sv,
                tempo_bar_chart_sv,
                estruturas_bar_chart_sv,
                acoes_bar_chart_sv,
                events_map_widget,
                density_chart_widget,
                hotspots_table_sv,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
